base_url = "https://pitkley.dev"
compile_sass = true
build_search_index = true
default_language = "en"

theme = "papaya"

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
banner_attribution = """&mdash; Photo by [Christian Lue](https://unsplash.com/@christianlue) on [Unsplash](https://unsplash.com/photos/4OBZT6oLVHk)"""

color_mode = "auto"
menu_items = [
    { name = "projects", url = "$LANG_BASE_URL/projects", show_recent = false },
    { name = "tags", url = "$LANG_BASE_URL/tags" },
]
pushed_projects = [
    "dfw",
]

[extra.ogp]
locale = "en_US"
first_name = "Pit"
gender = "male"
username = "pitkley"

[extra.social]
email = "blog@pitkley.de"
github = "pitkley"

[extra.images]
max_width = 2500

[extra.cdn.font_awesome]
url = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
integrity = "sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="

[languages]

[languages.en]
title = "pitkley.dev"
description = "Blog posts covering a mostly technical topics, serving as both my personal documentation and informative pieces for your edification. Also small showcases of my open-source projects."
generate_feed = true
feed_filename = "atom.xml"
taxonomies = [
    { name = "tags", feed = true, lang = "en" },
    { name = "categories", feed = true, lang = "en" },
]
[languages.en.translations]
projects = "Projects"
blog = "Blog"
about = "About"
recent_projects = "Recent Projects"
more_projects = "More Projects"
notable_projects = "Notable Projects"
recent_blog_posts = "Recent Blog Posts"
more_blog_posts = "More blog posts"
tag = "Tag"
tags = "Tags"
to_all_tags = "To all tags"
category = "Category"
categories = "Categories"
to_all_categories = "To all categories"
view_by = "View by"
other = "Other"
minute = "min"
prev_page = "To newer posts"
next_page = "To older posts"
date_format = "%B %e, %Y"
