name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: taiki-e/install-action@v2
      with:
        tool: zola@0.17.2
    - name: Checkout main
      uses: actions/checkout@v3.0.0
    - name: zola check --drafts
      run: zola check --drafts
    - name: zola build --drafts
      run: zola build --drafts
    - name: zola check
      run: zola check
    - name: zola build
      run: zola build
